### ISSUE TITLE
NUXT Support

### ISSUE THREAD

**Issue by DellanX** [dipscope/TypeManager.TS#16]
**Is your feature request related to a problem? Please describe.**

I'm trying to add this library to a NUXT App (so that I can build a native app).
The moment I add the @Type() decorator, NUXT throws a VITE compilation error:
```log
[vite-node] [VITE_ERROR] /utils/models/core/user.ts
at /utils/models/core/user.ts] {
  cause: {
    statusMessage: 'Vite Error',
    message: '[vite-node] [VITE_ERROR] /utils/models/core/user.ts',
    stack: '[vite-node] [VITE_ERROR] /utils/models/core/user.ts\n' +
      'at /utils/models/core/user.ts'
  },
  statusCode: 500,
  fatal: false,
  unhandled: false,
  statusMessage: 'Vite Error',
  data: undefined,
  __nuxt_error: true
}
```
Don't quite know why, and I do have the following in my .tsconfig file
```jsonc
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  // ...
  "compilerOptions": {
    // ...
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "useDefineForClassFields": false
  }
}
```

**Describe the solution you'd like**

There will likely need to be a module for adding type-manager into NUXT.

**Describe alternatives you've considered**

Kindof at a roadblock here.
May switch to the non-decorator method for the meantime, but the decorator method is quite pretty.

**Additional context**

**Comment by dpimonov** [comment]
Hi [DellanX](https://github.com/DellanX), thanks for using a library and continuously reporting issues. Which version of `TypeScript` are you using with `NUXT`? The only reason I see that it might be [related to this issue](https://github.com/dipscope/TypeManager.TS/issues/15) about `TypeScript` version 5. Library uses interface from core `TypeScript` and there should not be any issues when used with proper version and options. I don't have experience with `NUXT` so at least more details about what kind of error it encounters might help.

**Comment by DellanX** [comment]
Oh man, I uncovered a whole new can of worms (https://github.com/nuxt/nuxt/discussions/16185). NUXT doesn't like experimental decorators and ignores my tsconfig settings to enable it.

Your library is working fantastic, I just need to fight with NUXTs rollup and nitro mechanisms.

PS, thanks for all the great work on these libraries, they are 10/10. While me migrating to the entity system has definitely found a bunch of snags, it's a huge improvement overall! 😊

**Comment by DellanX** [comment]
Closing this issue, as it is basically a repeat of https://github.com/dipscope/TypeManager.TS/issues/15
If using experimental decorators, then refer to https://github.com/nuxt/nuxt/discussions/16185

I haven't solved the issue for myself yet.

**Comment by dpimonov** [comment]
Thanks for the feedback! 😊 

I hope you will find a solution. As you already mention going with declarative configuration might be an option. It works exactly the same and contains the same number of features. However amount of code is for sure larger as decorators hide all of this setup behind.
