### ISSUE TITLE
Entity Testing

### ISSUE THREAD

**Issue by DellanX** [dipscope/TypeManager.TS#32]
**Is your feature request related to a problem? Please describe.**

I am now at the point where I am developing unit tests for my codebase and am trying to determine the best way to determine how to unit test my Entity classes. To which, I realize there isn't any documentation for how to do so with this library. This issue is for two tasks:
1. To define a way to assert that the models are setup properly. I think a simple SerDes process would do just fine.
2. To document a testing process for developers using this library to validate their models. (I don't mind typing something up).

**Describe the solution you'd like**

For me, the testing I plan to add is just a simple Serialize Deserialize validation, for this I would do:
1. I would create a JSON payload such as what my server would transport (Since I am using JSON:API for my codebase)
2. Then create a test that deserialize the JSON Payload into an Entity and validate that each of its properties were deserialized properly.
4. Finally do the reverse, creating an Entity, serializing it, and validating it against the JSON payload.

I don't know if the infrastructure exists to interact with the TypeManager in such a way. Especially since the JsonApiEntityProvider is going to be a factor in the Serialization and Deserialization process. But I'd like to get your feedback. Again, I don't mind typing up documentation if desired.

**Describe alternatives you've considered**

I pretty much have testing for this at the feature level and could leave it like that. That said, I have had issues before that were caused by spelling issues or my declarators being off. It'd be nice to have a way to isolate the problems quickly.

This library already tests itself pretty well, thus the main requirement is to validate the way that I consume this library. I considered using type Metadata for this, but I think that is too low level to be useful, the tests would likely break often for changes unrelated to the application.
 
If I did really want to work around this, I could also:
- use the fetch-api mock injection and emplace my test boundary at the fetch api layer.
  (I use this for feature level, but this has a lot of overhead for validating the models)
- I could probably reverse engineer from the JsonApiEntityProvider how it interacts

**Additional context**

Testing is usually a hassle that gets put off for too long (I myself a Test Engineer am guilty of this), but it is a key step in ensuring quality code. I figure most users of this library have either developed a test process for their data models or put it off on the backburner.

I also understand if this is too unrelated of an issue, it is a problem I can definitely solve on my own time. Just figured it could be helpful for future developers.

**Comment by DellanX** [comment]
Here is my current snippet of code. Which I could document, but it is heavily specific to the JsonApiEntityProvider. To make this generic for other users, they'd probably need a method on the EntityStore to be able to do so. Let me know what you think? I think there are three paths forward:

1. Use a TypeManager interface method where the serialization/deserialization can be handled most abstractly. I don't think there is methodology for this yet, I figure this would need information from the EntityProvider to infer the transformation process.
2. An EntityStore interface method where the serialization/deserialization can be handled from the same library that the end-user would use. This would have access to the EntityProvider interface, but I also don't think the interface structure exists for this.
3. I could just leave this JSON:API specific implementation here (Might clean it up to be easier to understand)

Given that 1 and 2 may require changes to the interfaces, this might be something on the long backburner, till a non-breaking solution can be identified. Let me know what you think. This might just be a snippet I leave here for the time being.

* Once I have had time to implement a Pinia based EntityProvider, I may have better insights on how a generic test api could be created.

`user.test.ts`
```ts
import { setActivePinia, createPinia } from 'pinia';
import userJson from 's/models/core/user.json';
import { User } from '~/composables/models/core/user';
import { assertSerDesSelf } from 't/test-helpers/models/assert-ser-des';

const fetchMocker = createFetchMock(vi);
fetchMocker.enableMocks();

beforeEach(async () => {
    setActivePinia(createPinia());
});

describe('user model', () => {
    assertSerDesSelf({
        type: User,
        data: userJson
    })
});
```

`assert-ser-des.ts`
```ts
import type { Entity } from "@dipscope/entity-store";
import type { DataObject, DocumentObject } from "@dipscope/json-api-entity-provider";
import { TypeManager } from "@dipscope/type-manager";
import type { Nullable } from "~/composables/data/types";

export function assertSerDesSelf<T extends Entity>(config: {
    type: new () => T;
    data: DataObject;
}) {
    assertSerDes(
        {
            type: config.type,
            json: { data: config.data },
            entity() {
                const metadata = TypeManager.extractTypeMetadata(config.type);
                const deserializedInstance = useData().jsonApiEntityProvider.jsonApiAdapter.createDocumentObjectEntity(
                    metadata,
                    { data: config.data }
                );
                return deserializedInstance
            }
        },
        (entity: Nullable<T>) => {
            const metadata = TypeManager.extractTypeMetadata(config.type);
            const _entity = toValue(entity);
            const serializedInstance = _entity ? useData().jsonApiEntityProvider.jsonApiAdapter.createEntityDocumentObject<T>(
                metadata,
                _entity
            ) : _entity;
            expect(serializedInstance?.data).toStrictEqual(config.data);
        }
    )
}

export function assertSerDes<T extends Entity>(config: {
    type: new () => T;
    json: DocumentObject;
    entity: MaybeRefOrGetter<Nullable<T>>
},
    validateDeserializedObject: (deserializedInstance: Nullable<T>) => void,
    validateSerializedObject: (deserializedInstance: Nullable<DocumentObject>) => void = (json) => {
        expect(json?.data).toStrictEqual(config.json.data);
    }
) {
    const genericInstance = new config.type();
    it(`${genericInstance.type} deserializes`, () => {
        const metadata = TypeManager.extractTypeMetadata(config.type);
        const deserializedInstance = useData().jsonApiEntityProvider.jsonApiAdapter.createDocumentObjectEntity(
            metadata,
            config.json
        );
        validateDeserializedObject(deserializedInstance);
    });
    it(`${genericInstance.type} serializes`, () => {
        const metadata = TypeManager.extractTypeMetadata(config.type);
        const _entity = toValue(config.entity);
        const serializedInstance = _entity ? useData().jsonApiEntityProvider.jsonApiAdapter.createEntityDocumentObject(
            metadata,
            _entity
        ) : _entity;
        validateSerializedObject(serializedInstance);
    });
}
```

**Comment by dpimonov** [comment]
We can leave it here for now, I think. Maybe `JsonApiEntityProvider` is a better place, as `TypeManager` is more focused on reflection and serialization. Regarding `EntityStore`, I would like to keep the interface as simple as possible. The idea was not to expose serialization and deserialization methods, as the data objects differ between providers. Instead, we should provide a higher-level API where these details are abstracted by the provider.
